services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    MonsieurBiz\SyliusDashboardPlugin\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations}'
