services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    MonsieurBiz\SyliusDashboardPlugin\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations}'

    MonsieurBiz\SyliusDashboardPlugin\Controller\:
        resource: '../../Controller'
        tags: [ 'controller.service_arguments' ]
